services:
  gridmonitor.api:
    image: ${DOCKER_REGISTRY-}gridmonitorapi
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - "8020:8020"

  postgres:
    image: postgres:15
    container_name: gridmonitor-db
    environment:
      POSTGRES_DB: gridmonitor
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
 
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: gridmonitor
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
