// <auto-generated />
using System;
using GridMonitor.Infrastructure.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412184610_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridMonitor.Domain.Entities.AlertChannel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("text");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("AlertChannels", "dbo");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.AlertLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("IdemptotencyKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Stage")
                        .HasColumnType("smallint");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SentAt");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("AlertLogs", "dbo");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.AlertSubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("AlertMinutesBefore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)30);

                    b.Property<string>("AlertSubscriptionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SuburbId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("AlertSubscriptionId");

                    b.HasIndex("SuburbId");

                    b.HasIndex("UserId", "SuburbId");

                    b.ToTable("AlertSubscriptions", "dbo");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.ApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyCallLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys", "dbo");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EskomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("integer");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EskomId")
                        .IsUnique();

                    b.HasIndex("ProvinceId");

                    b.ToTable("Municipalities", "dbo");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EskomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastSyncedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EskomId")
                        .IsUnique();

                    b.ToTable("Provinces", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EskomId = 1,
                            LastSyncedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eastern Cape"
                        },
                        new
                        {
                            Id = 2,
                            EskomId = 2,
                            LastSyncedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Free State"
                        },
                        new
                        {
                            Id = 3,
                            EskomId = 3,
                            LastSyncedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gauteng"
                        },
                        new
                        {
                            Id = 4,
                            EskomId = 4,
                            LastSyncedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "KwaZulu-Natal"
                        },
                        new
                        {
                            Id = 5,
                            EskomId = 5,
                            LastSyncedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Limpopo"
                        },
                        new
                        {
                            Id = 6,
                            EskomId = 6,
                            LastSyncedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mpumalanga"
                        },
                        new
                        {
                            Id = 7,
                            EskomId = 7,
                            LastSyncedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "North West"
                        },
                        new
                        {
                            Id = 8,
                            EskomId = 8,
                            LastSyncedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Northern Cape"
                        },
                        new
                        {
                            Id = 9,
                            EskomId = 9,
                            LastSyncedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Western Cape"
                        });
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.ScheduleSlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DayLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<short>("Stage")
                        .HasColumnType("smallint");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("SuburbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SuburbId");

                    b.HasIndex("SuburbId", "Stage", "DayOfWeek", "StartTime")
                        .IsUnique();

                    b.ToTable("ScheduleSlots", "dbo");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.StageSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<short>("Stage")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("StageSnapshots", "dbo");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.Suburb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EskomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EskomId")
                        .IsUnique();

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("Name");

                    b.ToTable("Suburbs", "dbo");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.SyncRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MunicipalitiesProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SuburbProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("SyncRuns", "dbo");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<byte>("PricingTier")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.HasIndex("Email", "KeycloakId")
                        .IsUnique();

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.AlertChannel", b =>
                {
                    b.HasOne("GridMonitor.Domain.Entities.AlertSubscription", "Subscription")
                        .WithMany("Channels")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.AlertLog", b =>
                {
                    b.HasOne("GridMonitor.Domain.Entities.AlertSubscription", "Subscription")
                        .WithMany("Logs")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.AlertSubscription", b =>
                {
                    b.HasOne("GridMonitor.Domain.Entities.AlertSubscription", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("AlertSubscriptionId");

                    b.HasOne("GridMonitor.Domain.Entities.Suburb", "Suburb")
                        .WithMany()
                        .HasForeignKey("SuburbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GridMonitor.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Suburb");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("GridMonitor.Domain.Entities.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.Municipality", b =>
                {
                    b.HasOne("GridMonitor.Domain.Entities.Province", "Province")
                        .WithMany("Municipalities")
                        .HasForeignKey("ProvinceId")
                        .HasPrincipalKey("EskomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.ScheduleSlot", b =>
                {
                    b.HasOne("GridMonitor.Domain.Entities.Suburb", "Suburb")
                        .WithMany("Slots")
                        .HasForeignKey("SuburbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suburb");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.Suburb", b =>
                {
                    b.HasOne("GridMonitor.Domain.Entities.Municipality", "Municipality")
                        .WithMany("Suburbs")
                        .HasForeignKey("MunicipalityId")
                        .HasPrincipalKey("EskomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.AlertSubscription", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Logs");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.Municipality", b =>
                {
                    b.Navigation("Suburbs");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.Province", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.Suburb", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("GridMonitor.Domain.Entities.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
